apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blog
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: blog
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/fklein82/tbs-blog-demo.git
      ref:
        branch: main